CREATE TABLE correct
(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL ,
    PRIMARY KEY (id)

) ENGINE = InnoDB;

CREATE TABLE wrong
(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL ,
    PRIMARY KEY (id)

) ENGINE = InnoDB;